# Generated by Django 2.2.2 on 2019-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='book_name',
            field=models.CharField(help_text='Book Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='num_of_books',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1),
        ),
    ]
