# Generated by Django 2.2.2 on 2019-06-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190620_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='book_name',
            field=models.ForeignKey(help_text='Book Took', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book'),
        ),
    ]
